name: The Real Final RDP (v19 - Linux Version)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # گۆڕدراوە بۆ ئوبونتو
    timeout-minutes: 360
    steps:
      - name: Install and Configure RDP
        run: |
          # دامەزراندنی xfce4 و xrdp
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 xfce4-goodies xrdp
          sudo systemctl enable xrdp
          
          # ڕێکخستنی xrdp بۆ بەکارهێنانی xfce
          echo xfce4-session > ~/.xsession
          sudo cp ~/.xsession /etc/skel
          sudo sed -i 's/test -x \/etc\/X11\/Xsession && exec \/etc\/X11\/Xsession/exec \/bin\/sh \/etc\/X11\/Xsession/' /etc/xrdp/startwm.sh
          
          # کردنەوەی پۆرتی 3389
          sudo ufw allow 3389/tcp
          sudo systemctl restart xrdp

      - name: Set Timezone
        run: sudo timedatectl set-timezone "Asia/Baghdad" # گۆڕدراوە بۆ کاتی بەغدا

      - name: Create User
        run: |
          PASSWORD="Yusf@2000#RDP"
          sudo useradd -m -s /bin/bash yusf2000
          echo "yusf2000:$PASSWORD" | sudo chpasswd
          sudo adduser yusf2000 sudo
          sudo adduser yusf2000 xrdp
          
          # دروستکردنی فۆڵدەرەکان (ئەگەر پێویست بوو، useradd -m خۆی دروستیان دەکات)
          sudo -u yusf2000 mkdir -p /home/yusf2000/Desktop /home/yusf2000/Documents /home/yusf2000/Downloads
          
          echo "RDP_USER=yusf2000" >> $GITHUB_ENV
          echo "RDP_PASS=$PASSWORD" >> $GITHUB_ENV

      - name: Install Software
        run: |
          # دامەزراندنی Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f -y # بۆ چارەسەرکردنی dependency
          rm google-chrome-stable_current_amd64.deb
          
          # دامەزراندنی VS Code, 7zip, rclone
          sudo apt-get install -y wget gpg
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
          sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
          sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
          rm -f packages.microsoft.gpg
          
          sudo apt-get update
          sudo apt-get install -y code p7zip-full rclone

      - name: Setup Rclone and Download
        if: ${{ secrets.RCLONE_SA_JSON != '' }} # سینتاکسی if چاککراوە
        env:
          RCLONE_SA_JSON: ${{ secrets.RCLONE_SA_JSON }}
        run: |
          echo "Service Account JSON found. Configuring rclone..."
          sudo -u yusf2000 mkdir -p /home/yusf2000/.config/rclone
          echo "[gdrive]" | sudo tee /home/yusf2000/.config/rclone/rclone.conf
          echo "type = drive" | sudo tee -a /home/yusf2000/.config/rclone/rclone.conf
          echo "service_account_file = /home/yusf2000/sa.json" | sudo tee -a /home/yusf2000/.config/rclone/rclone.conf
          echo "$RCLONE_SA_JSON" | sudo tee /home/yusf2000/sa.json
          sudo chown yusf2000:yusf2000 /home/yusf2000/sa.json
          
          echo "Downloading files from Google Drive..."
          sudo -u yusf2000 rclone sync "gdrive:My_RDP_Backup/Desktop" "/home/yusf2000/Desktop" --create-empty-src-dirs --ignore-errors
          sudo -u yusf2000 rclone sync "gdrive:My_RDP_Backup/Documents" "/home/yusf2000/Documents" --create-empty-src-dirs --ignore-errors
          sudo -u yusf2000 rclone sync "gdrive:My_RDP_Backup/Downloads" "/home/yusf2000/Downloads" --create-empty-src-dirs --ignore-errors
        continue-on-error: true

      - name: Connect to Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$GITHUB_RUN_ID
          TS_IP=$(tailscale ip -4)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: Display RDP Info
        run: |
          echo "========================================"
          echo "RDP Address: ${{ env.TAILSCALE_IP }}"
          echo "Username:    ${{ env.RDP_USER }}"
          echo "Password:    ${{ env.RDP_PASS }}"
          echo "========================================"
          
      - name: Keep Alive
        run: |
          while true; do
            echo "[$(date)] Session is active."
            sleep 60
          done

      - name: Upload Files to Cloud
        if: ${{ always() && secrets.RCLONE_SA_JSON != '' }} # سینتاکسی if چاککراوە
        env:
          RCLONE_SA_JSON: ${{ secrets.RCLONE_SA_JSON }}
        run: |
          echo "Service Account JSON found. Uploading files..."
          sudo -u yusf2000 rclone sync "/home/yusf2000/Desktop" "gdrive:My_RDP_Backup/Desktop" --create-empty-src-dirs --ignore-errors
          sudo -u yusf2000 rclone sync "/home/yusf2000/Documents" "gdrive:My_RDP_Backup/Documents" --create-empty-src-dirs --ignore-errors
          sudo -u yusf2000 rclone sync "/home/yusf2000/Downloads" "gdrive:My_RDP_Backup/Downloads" --create-empty-src-dirs --ignore-errors
          echo "Upload complete."
        continue-on-error: true
